# Generated by Django 5.1.3 on 2024-12-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_id_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_use',
        ),
    ]
